conky.config = {
    alignment = 'top_middle',
    background = false,
    border_width = 0,
    double_buffer = false,
    no_buffers = false,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    gap_x = 0,
    gap_y = 100,
    update_interval = 60,
    use_xft = true,
    xftalpha = 1,
}

conky.text = [[
${alignc}${color FFAA00}${font Orbitron:bold:size=13}${time %A}${font}
${alignc}${color FFAA00}${font Orbitron:size=10}${time %d %B, %Y}${font}
${color}
${alignc}${color FFAA00}${font Orbitron:bold:size=48}${time %H:%M}${font}
${color}
${alignc}${color FFAA00}${font Orbitron:size=10} ${battery_percent BAT0}%  |  ${battery_status BAT0}${font}
${alignc}${color FFAA00}${battery_bar 8,200 BAT0}
]]
